package models;
// Generated 24 mars 2014 10:24:07 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Centres generated by hbm2java
 */
@Entity
@Table(name="centres")
public class Centres  implements java.io.Serializable {

	
	private static final long serialVersionUID = -731468984861123772L;
	@Id 
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id")
	private Integer centerId;
	
	@Column(name = "Adresse", columnDefinition="varchar(80) default '' ", nullable=true)
    private String centerAddress;
	
	@Column(name = "Arrondissement", columnDefinition="varchar(60) default '' ", nullable=true)
    private String centerArrondissement;
	
	@Column(name = "Boite_postale", columnDefinition="varchar(10) default '' ", nullable=true)
    private String centerBp;
	
	@Column(name = "Code", columnDefinition="varchar(10) default '' ", nullable=true)
    private String centerCode;
	
	@Column(name = "Circonscription", columnDefinition="varchar(80) default '' ", nullable=true)
    private String centerCollectivite;
	
	@Column(name = "Nom_Commune", columnDefinition="varchar(80) default '' ", nullable=true)
    private String commune;
	
	@Column(name = "Date_Install", columnDefinition="varchar(80) default '' ", nullable=true)
    private String date_Install;
	
	@Column(name = "Departement", columnDefinition="varchar(40) default '' ", nullable=true)
    private String centerDepartement;
    
	@Column(name = "Mail", columnDefinition="varchar(40) default '' ", nullable=true)
	private String centerMail;
	
	@Column(name = "Nom", columnDefinition="varchar(80) default '' ", nullable=true)
    private String centerName;
	
	@Column(name = "Telephone", columnDefinition="varchar(20) default '' ", nullable=true)
    private String centerPhone;
	
	@Column(name = "Centre_principal", columnDefinition="varchar(40) default '' ", nullable=true)
    private String mainCenter;
	
	@Column(name = "Region", columnDefinition="varchar(50) default '' ", nullable=true)
    private String centerRegion;
	
	@Column(name = "Type", columnDefinition="varchar(30) default '' ", nullable=true)
    private String centerType;
	
	@Column(name = "Annee", columnDefinition="varchar(5) default '' ", nullable=false)
    private String anneeRegistre;
	
	@Column(name = "Nom_maire", columnDefinition="varchar(40) default '' ", nullable=false)
    private String nom_maire;
	
	@Column(name = "Prenom_maire", columnDefinition="varchar(60) default '' ", nullable=false)
    private String prenom_maire;
	
	@Column(name = "Description", columnDefinition="LONGTEXT ", nullable=false)
    private String description;
	
	@Column(name = "Date_acces", columnDefinition="varchar(20) default '' ", nullable=false)
    private String acces;
	
	
	@OneToMany(mappedBy="centre")
	private List<Users> userList;
	
	private Date accesD;


	public Centres() {
    }

    public Centres(String centerAddress, String centerArrondissement, String centerBp, String centerCode, String centerCollectivite, String centerDepartement, 
    		String centerMail, String centerName, String centerPhone, String mainCenter, String centerRegion, String centerType, String anneeRegistre, 
    		String nom_maire, String prenom_maire, String description, String acces, String commune, String date_Install) {
       this.centerAddress = centerAddress;
       this.centerArrondissement = centerArrondissement;
       this.centerBp = centerBp;
       this.centerCode = centerCode;
       this.centerCollectivite = centerCollectivite;
       this.centerDepartement = centerDepartement;
       this.centerMail = centerMail;
       this.centerName = centerName;
       this.centerPhone = centerPhone;
       this.mainCenter = mainCenter;
       this.centerRegion = centerRegion;
       this.centerType = centerType;
       this.anneeRegistre = anneeRegistre;
       this.nom_maire = nom_maire;
       this.prenom_maire = prenom_maire;
       this.description = description;
       this.acces = acces;
       this.commune = commune;
       this.date_Install = date_Install;
    }
   

    public Integer getCenterId() {
        return this.centerId;
    }
    
    public void setCenterId(Integer centerId) {
        this.centerId = centerId;
    }

    public String getCenterAddress() {
        return this.centerAddress;
    }
    
    public void setCenterAddress(String centerAddress) {
        this.centerAddress = centerAddress;
    }

    public String getCenterArrondissement() {
        return this.centerArrondissement;
    }
    
    public void setCenterArrondissement(String centerArrondissement) {
        this.centerArrondissement = centerArrondissement;
    }

    
    public String getCenterBp() {
        return this.centerBp;
    }
    
    public void setCenterBp(String centerBp) {
        this.centerBp = centerBp;
    }


    public String getCenterCode() {
        return this.centerCode;
    }
    
    public void setCenterCode(String centerCode) {
        this.centerCode = centerCode;
    }

    public String getCenterCollectivite() {
        return this.centerCollectivite;
    }
    
    public void setCenterCollectivite(String centerCollectivite) {
        this.centerCollectivite = centerCollectivite;
    }

    public String getCenterDepartement() {
        return this.centerDepartement;
    }
    
    public void setCenterDepartement(String centerDepartement) {
        this.centerDepartement = centerDepartement;
    }

    public String getCenterMail() {
        return this.centerMail;
    }
    
    public void setCenterMail(String centerMail) {
        this.centerMail = centerMail;
    }

    public String getCenterName() {
        return this.centerName;
    }
    
    public void setCenterName(String centerName) {
        this.centerName = centerName;
    }

    public String getCenterPhone() {
        return this.centerPhone;
    }
    
    public void setCenterPhone(String centerPhone) {
        this.centerPhone = centerPhone;
    }

    
    public String getMainCenter() {
        return this.mainCenter;
    }
    
    public void setMainCenter(String mainCenter) {
        this.mainCenter = mainCenter;
    }

    public String getCenterRegion() {
        return this.centerRegion;
    }
    
    public void setCenterRegion(String centerRegion) {
        this.centerRegion = centerRegion;
    }

    public String getCenterType() {
        return this.centerType;
    }
    
    public void setCenterType(String centerType) {
        this.centerType = centerType;
    }
 
    public List<Users> getUserList() {
		return userList;
	}

	public void setUserList(List<Users> userList) {
		this.userList = userList;
	}

	public String getAnneeRegistre() {
		return anneeRegistre;
	}

	public void setAnneeRegistre(String anneeRegistre) {
		this.anneeRegistre = anneeRegistre;
	}

	/**
	 * @return the nom_maire
	 */
	public String getNom_maire() {
		return nom_maire;
	}

	/**
	 * @param nom_maire the nom_maire to set
	 */
	public void setNom_maire(String nom_maire) {
		this.nom_maire = nom_maire;
	}

	/**
	 * @return the prenom_maire
	 */
	public String getPrenom_maire() {
		return prenom_maire;
	}

	/**
	 * @param prenom_maire the prenom_maire to set
	 */
	public void setPrenom_maire(String prenom_maire) {
		this.prenom_maire = prenom_maire;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the accesD
	 */
	public Date getAccesD() {
		return accesD;
	}

	/**
	 * @param accesD the accesD to set
	 */
	public void setAccesD(Date accesD) {
		this.accesD = accesD;
	}

	/**
	 * @return the acces
	 */
	public String getAcces() {
		return acces;
	}

	/**
	 * @param acces the acces to set
	 */
	public void setAcces(String acces) {
		this.acces = acces;
	}

	/**
	 * @return the commune
	 */
	public String getCommune() {
		return commune;
	}

	/**
	 * @param commune the commune to set
	 */
	public void setCommune(String commune) {
		this.commune = commune;
	}

	/**
	 * @return the date_Install
	 */
	public String getDate_Install() {
		return date_Install;
	}

	/**
	 * @param date_Install the date_Install to set
	 */
	public void setDate_Install(String date_Install) {
		this.date_Install = date_Install;
	}
	
	
	

}


