package models;
// Generated 24 mars 2014 10:24:07 by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Declaration generated by hbm2java
 */
@Entity
@Table(name="declaration_naissance")
public class DeclarationNaissance  implements java.io.Serializable {


	private static final long serialVersionUID = -1367653933236455676L;
	@Id 
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "declaration_id")
	private Integer id;
	
	@Column(name = "numero_acte", columnDefinition="varchar(11) default '' ")
	private String numero_acte;
	
	@Column(name = "prenom_enfant", columnDefinition="varchar(60) default '' ", nullable=false)
	private String prenom_enfant;
	
	@Column(name = "nom_enfant", columnDefinition="varchar(40) default '' ", nullable=false)
	private String nom_enfant;
	
	@Column(name = "sexe_enfant", columnDefinition="varchar(20) default '' ", nullable=false)
	private String sexe;
	
	@Column(name = "date_naissance_enfant", columnDefinition="varchar(20) default '' ", nullable=false)
	private String date_naissance_enfant;
	
	@Column(name = "heure_naissance_enfant", columnDefinition="varchar(10) default '' ", nullable=false)
	private String heure_naissance_enfant;
	
	@Column(name = "lieu_naissance_enfant", columnDefinition="varchar(80) default '' ", nullable=false)
	private String lieu_naissance_enfant;
	
	@Column(name = "pays_naissance_enfant", columnDefinition="varchar(40) default '' ")
	private String pays_naissance_enfanr;
	
	@Column(name = "formation_sanitaire", columnDefinition="varchar(50) default '' ")
	private String formation_sanitaire;
	
	@Column(name = "prenom_pere", columnDefinition="varchar(60) default '' ")
	private String prenom_pere;
	
	@Column(name = "nom_pere", columnDefinition="varchar(40) default '' ")
	private String nom_pere;
	
	@Column(name = "date_naissance_pere", columnDefinition="varchar(20) default '' ")
	private String date_naissance_pere;
	
	@Column(name = "lieu_naissance_pere", columnDefinition="varchar(80) default '' ")
	private String lieu_naissance_pere;
	
	@Column(name = "profession_pere", columnDefinition="varchar(20) default '' ")
	private String profession_pere;
	
	@Column(name = "domicile_pere", columnDefinition="varchar(80) default '' ")
	private String domicile_pere;
	
	@Column(name = "prenom_mere", columnDefinition="varchar(60) default '' ", nullable=false)
	private String prenom_mere;
	
	@Column(name = "nom_mere", columnDefinition="varchar(40) default '' ", nullable=false)
	private String nom_mere;
	
	@Column(name = "date_naissance_mere", columnDefinition="varchar(20) default '' ", nullable=false)
	private String date_naissance_mere;
	
	@Column(name = "lieu_naissance_mere", columnDefinition="varchar(80) default '' ", nullable=false)
	private String lieu_naissance_mere;
	
	@Column(name = "profession_mere", columnDefinition="varchar(60) default '' ", nullable=false)
	private String profession_mere;
	
	@Column(name = "domicile_mere", columnDefinition="varchar(80) default '' ", nullable=false)
	private String domicile_mere;
	
	@Column(name = "date_creation", columnDefinition="varchar(20) default '' ", nullable=false)
	private String date_creation;
	
	@Column(name = "date_modification", columnDefinition="varchar(20) default '' ")
	private String date_modification;
	
	@Column(name = "etat", columnDefinition="varchar(20) default '' ", nullable=false)
	private String etat;
	
	@Column(name = "Type_declaration", columnDefinition="varchar(30) default '' ", nullable=false)
	private String type_declaration;
	
	@Column(name = "declarant", columnDefinition="varchar(20) default '' ", nullable=false)
	private String declarant;
	
	@Column(name = "prenom_declarant", columnDefinition="varchar(60) default '' ")
	private String prenom_declarant;
	
	@Column(name = "nom_declarant", columnDefinition="varchar(40) default '' ")
	private String nom_declarant;
	
	@Column(name = "adresse_declarant", columnDefinition="varchar(80) default '' ")
	private String adresse_declarant;
	
	@Column(name = "profession_declarant", columnDefinition="varchar(60) default '' ")
	private String profession_declarant;
	
	@Column(name = "domicile_declarant", columnDefinition="varchar(60) default '' ")
	private String domicile_declarant;
	
	@Column(name = "num_identification_declarant", columnDefinition="varchar(20) default '' ")
	private String num_identification_declarant;
	
	@Column(name = "numero_jugement", columnDefinition="varchar(11) default '' ")
	private String numero_jugement;
	
	@Column(name = "date_jugement", columnDefinition="varchar(20) default '' ")
	private String date_jugement;
	
	@Column(name = "tribunal", columnDefinition="varchar(40) default '' ")
	private String tribunal;
	
	@Column(name = "mention_marginale", columnDefinition="LONGTEXT")
	private String mention_marginale;
	
	private Date date_naissanceE;
	private Date date_naissanceM;
	
	private Date date_naissanceP;
	private Date date_j;
	private Date heure_naissanceE;

	@ManyToOne
	(
			cascade={CascadeType.PERSIST, CascadeType.MERGE}
	)
	@JoinColumn(name="createurNaissance")
	private Users createurNaissance;
	
	@ManyToOne
	(
			cascade={CascadeType.PERSIST, CascadeType.MERGE}
	)
	@JoinColumn(name="modificateurNaissance")
	private Users modificateurNaissance;
	
	@ManyToOne
	(
			cascade={CascadeType.PERSIST, CascadeType.MERGE}
	)
	@JoinColumn(name="validateurNaissance")
	private Users validateurNaissance;
	
	

	public DeclarationNaissance() {
	}



	public DeclarationNaissance(String numero_acte, String prenom_enfant,
			String nom_enfant, String sexe, String date_naissance_enfant,
			String heure_naissance_enfant, String lieu_naissance_enfant,
			String pays_naissance_enfanr, String formation_sanitaire,
			String prenom_pere, String nom_pere, String date_naissance_pere,
			String lieu_naissance_pere, String profession_pere,
			String domicile_pere, String prenom_mere, String nom_mere,
			String date_naissance_mere, String lieu_naissance_mere,
			String profession_mere, String domicile_mere, String date_creation,
			String date_modification, String etat, String type_declaration,
			String declarant, String prenom_declarant, String nom_declarant,
			String adresse_declarant, String profession_declarant,
			String domicile_declarant, String num_identification_declarant,
			String numero_jugement, String date_jugement, String tribunal,
			String mention_marginale, Users createurNaissance, Users modificateur_id,
			Users validateurNaissance) {
		super();
		this.numero_acte = numero_acte;
		this.prenom_enfant = prenom_enfant;
		this.nom_enfant = nom_enfant;
		this.sexe = sexe;
		this.date_naissance_enfant = date_naissance_enfant;
		this.heure_naissance_enfant = heure_naissance_enfant;
		this.lieu_naissance_enfant = lieu_naissance_enfant;
		this.pays_naissance_enfanr = pays_naissance_enfanr;
		this.formation_sanitaire = formation_sanitaire;
		this.prenom_pere = prenom_pere;
		this.nom_pere = nom_pere;
		this.date_naissance_pere = date_naissance_pere;
		this.lieu_naissance_pere = lieu_naissance_pere;
		this.profession_pere = profession_pere;
		this.domicile_pere = domicile_pere;
		this.prenom_mere = prenom_mere;
		this.nom_mere = nom_mere;
		this.date_naissance_mere = date_naissance_mere;
		this.lieu_naissance_mere = lieu_naissance_mere;
		this.profession_mere = profession_mere;
		this.domicile_mere = domicile_mere;
		this.date_creation = date_creation;
		this.date_modification = date_modification;
		this.etat = etat;
		this.type_declaration = type_declaration;
		this.declarant = declarant;
		this.prenom_declarant = prenom_declarant;
		this.nom_declarant = nom_declarant;
		this.adresse_declarant = adresse_declarant;
		this.profession_declarant = profession_declarant;
		this.domicile_declarant = domicile_declarant;
		this.num_identification_declarant = num_identification_declarant;
		this.numero_jugement = numero_jugement;
		this.date_jugement = date_jugement;
		this.tribunal = tribunal;
		this.mention_marginale = mention_marginale;
		this.createurNaissance = createurNaissance;
		this.modificateurNaissance = modificateur_id;
		this.validateurNaissance = validateurNaissance;
	}



	public Integer getId() {
		return id;
	}



	public void setId(Integer id) {
		this.id = id;
	}



	public String getNumero_acte() {
		return numero_acte;
	}



	public void setNumero_acte(String numero_acte) {
		this.numero_acte = numero_acte;
	}



	public String getPrenom_enfant() {
		return prenom_enfant;
	}



	public void setPrenom_enfant(String prenom_enfant) {
		this.prenom_enfant = prenom_enfant;
	}



	public String getNom_enfant() {
		return nom_enfant;
	}



	public void setNom_enfant(String nom_enfant) {
		this.nom_enfant = nom_enfant;
	}



	public String getSexe() {
		return sexe;
	}



	public void setSexe(String sexe) {
		this.sexe = sexe;
	}



	public String getDate_naissance_enfant() {
		return date_naissance_enfant;
	}



	public void setDate_naissance_enfant(String date_naissance_enfant) {
		this.date_naissance_enfant = date_naissance_enfant;
	}



	public String getHeure_naissance_enfant() {
		return heure_naissance_enfant;
	}



	public void setHeure_naissance_enfant(String heure_naissance_enfant) {
		this.heure_naissance_enfant = heure_naissance_enfant;
	}



	public String getLieu_naissance_enfant() {
		return lieu_naissance_enfant;
	}



	public void setLieu_naissance_enfant(String lieu_naissance_enfant) {
		this.lieu_naissance_enfant = lieu_naissance_enfant;
	}



	public String getPays_naissance_enfanr() {
		return pays_naissance_enfanr;
	}



	public void setPays_naissance_enfanr(String pays_naissance_enfanr) {
		this.pays_naissance_enfanr = pays_naissance_enfanr;
	}



	public String getFormation_sanitaire() {
		return formation_sanitaire;
	}



	public void setFormation_sanitaire(String formation_sanitaire) {
		this.formation_sanitaire = formation_sanitaire;
	}



	public String getPrenom_pere() {
		return prenom_pere;
	}



	public void setPrenom_pere(String prenom_pere) {
		this.prenom_pere = prenom_pere;
	}



	public String getNom_pere() {
		return nom_pere;
	}



	public void setNom_pere(String nom_pere) {
		this.nom_pere = nom_pere;
	}



	public String getDate_naissance_pere() {
		return date_naissance_pere;
	}



	public void setDate_naissance_pere(String date_naissance_pere) {
		this.date_naissance_pere = date_naissance_pere;
	}



	public String getLieu_naissance_pere() {
		return lieu_naissance_pere;
	}



	public void setLieu_naissance_pere(String lieu_naissance_pere) {
		this.lieu_naissance_pere = lieu_naissance_pere;
	}



	public String getProfession_pere() {
		return profession_pere;
	}



	public void setProfession_pere(String profession_pere) {
		this.profession_pere = profession_pere;
	}



	public String getDomicile_pere() {
		return domicile_pere;
	}



	public void setDomicile_pere(String domicile_pere) {
		this.domicile_pere = domicile_pere;
	}



	public String getPrenom_mere() {
		return prenom_mere;
	}



	public void setPrenom_mere(String prenom_mere) {
		this.prenom_mere = prenom_mere;
	}



	public String getNom_mere() {
		return nom_mere;
	}



	public void setNom_mere(String nom_mere) {
		this.nom_mere = nom_mere;
	}



	public String getDate_naissance_mere() {
		return date_naissance_mere;
	}



	public void setDate_naissance_mere(String date_naissance_mere) {
		this.date_naissance_mere = date_naissance_mere;
	}



	public String getLieu_naissance_mere() {
		return lieu_naissance_mere;
	}



	public void setLieu_naissance_mere(String lieu_naissance_mere) {
		this.lieu_naissance_mere = lieu_naissance_mere;
	}



	public String getProfession_mere() {
		return profession_mere;
	}



	public void setProfession_mere(String profession_mere) {
		this.profession_mere = profession_mere;
	}



	public String getDomicile_mere() {
		return domicile_mere;
	}



	public void setDomicile_mere(String domicile_mere) {
		this.domicile_mere = domicile_mere;
	}



	public String getDate_creation() {
		return date_creation;
	}



	public void setDate_creation(String date_creation) {
		this.date_creation = date_creation;
	}



	public String getDate_modification() {
		return date_modification;
	}



	public void setDate_modification(String date_modification) {
		this.date_modification = date_modification;
	}



	public String getEtat() {
		return etat;
	}



	public void setEtat(String etat) {
		this.etat = etat;
	}



	public String getType_declaration() {
		return type_declaration;
	}



	public void setType_declaration(String type_declaration) {
		this.type_declaration = type_declaration;
	}



	public String getDeclarant() {
		return declarant;
	}



	public void setDeclarant(String declarant) {
		this.declarant = declarant;
	}



	public String getPrenom_declarant() {
		return prenom_declarant;
	}



	public void setPrenom_declarant(String prenom_declarant) {
		this.prenom_declarant = prenom_declarant;
	}



	public String getNom_declarant() {
		return nom_declarant;
	}



	public void setNom_declarant(String nom_declarant) {
		this.nom_declarant = nom_declarant;
	}



	public String getAdresse_declarant() {
		return adresse_declarant;
	}



	public void setAdresse_declarant(String adresse_declarant) {
		this.adresse_declarant = adresse_declarant;
	}



	public String getProfession_declarant() {
		return profession_declarant;
	}



	public void setProfession_declarant(String profession_declarant) {
		this.profession_declarant = profession_declarant;
	}



	public String getDomicile_declarant() {
		return domicile_declarant;
	}



	public void setDomicile_declarant(String domicile_declarant) {
		this.domicile_declarant = domicile_declarant;
	}



	public String getNum_identification_declarant() {
		return num_identification_declarant;
	}



	public void setNum_identification_declarant(String num_identification_declarant) {
		this.num_identification_declarant = num_identification_declarant;
	}



	public String getNumero_jugement() {
		return numero_jugement;
	}



	public void setNumero_jugement(String numero_jugement) {
		this.numero_jugement = numero_jugement;
	}



	public String getDate_jugement() {
		return date_jugement;
	}



	public void setDate_jugement(String date_jugement) {
		this.date_jugement = date_jugement;
	}



	public String getTribunal() {
		return tribunal;
	}



	public void setTribunal(String tribunal) {
		this.tribunal = tribunal;
	}



	public String getMention_marginale() {
		return mention_marginale;
	}



	public void setMention_marginale(String mention_marginale) {
		this.mention_marginale = mention_marginale;
	}



	public Date getDate_naissanceE() {
		return date_naissanceE;
	}



	public void setDate_naissanceE(Date date_naissanceE) {
		this.date_naissanceE = date_naissanceE;
	}



	public Date getDate_naissanceM() {
		return date_naissanceM;
	}



	public void setDate_naissanceM(Date date_naissanceM) {
		this.date_naissanceM = date_naissanceM;
	}



	public Date getDate_naissanceP() {
		return date_naissanceP;
	}



	public void setDate_naissanceP(Date date_naissanceP) {
		this.date_naissanceP = date_naissanceP;
	}



	public Date getDate_j() {
		return date_j;
	}



	public void setDate_j(Date date_j) {
		this.date_j = date_j;
	}


	public Date getHeure_naissanceE() {
		return heure_naissanceE;
	}



	public void setHeure_naissanceE(Date heure_naissanceE) {
		this.heure_naissanceE = heure_naissanceE;
	}
	
	
	public Users getCreateurNaissance() {
		return createurNaissance;
	}



	public void setCreateurNaissance(Users createurNaissance) {
		this.createurNaissance = createurNaissance;
	}



	public Users getModificateurNaissance() {
		return modificateurNaissance;
	}



	public void setModificateurNaissance(Users modificateurNaissance) {
		this.modificateurNaissance = modificateurNaissance;
	}



	public Users getValidateurNaissance() {
		return validateurNaissance;
	}



	public void setValidateurNaissance(Users validateurNaissance) {
		this.validateurNaissance = validateurNaissance;
	}



	
}


