package models;
// Generated 24 mars 2014 10:24:07 by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DeclarationDece generated by hbm2java
 */
@Entity
@Table(name="declaration_deces")
public class DeclarationDeces  implements java.io.Serializable {


	private static final long serialVersionUID = 1353061056779772342L;
	@Id 
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id")
	private Integer id;
	
	@Column(name = "date_deces", columnDefinition="varchar(20) default '' ", nullable=false)
	private String date_deces;
	
	@Column(name = "heure_deces", columnDefinition="varchar(10) default '' ", nullable=false)
	private String heure_deces;
	
	@Column(name = "lieu_deces", columnDefinition="varchar(80) default '' ", nullable=false)
	private String lieu_deces;
	
	@Column(name = "formation_sanitaire", columnDefinition="varchar(80) default '' ", nullable=false)
	private String formation_sanitaire;
	
	@Column(name = "numero_acte", columnDefinition="varchar(11) default '' ", nullable=true)
	private String numero_acte;
	
	@Column(name = "prenom_defunt", columnDefinition="varchar(60) default '' ", nullable=false)
	private String prenom_defunt;
	
	@Column(name = "nom_defunt", columnDefinition="varchar(40) default '' ", nullable=false)
	private String nom_defunt;
	
	@Column(name = "sexe_defunt", columnDefinition="varchar(20) default '' ", nullable=false)
	private String sexe_defunt;
	
	@Column(name = "date_naissance_defunt", columnDefinition="varchar(20) default '' ", nullable=false)
	private String date_naissance_defunt;
	
	@Column(name = "lieu_naissance_defunt", columnDefinition="varchar(80) default '' ", nullable=false)
	private String lieu_naissance_defunt;
	
	@Column(name = "profession_defunt", columnDefinition="varchar(60) default '' ", nullable=true)
	private String profession_defunt;
	
	@Column(name = "domicile_defunt", columnDefinition="varchar(60) default '' ", nullable=true)
	private String domicile_defunt;
	
	@Column(name = "marie_a", columnDefinition="varchar(80) default '' ", nullable=true)
	private String marie_a;
	
	@Column(name = "prenom_pere", columnDefinition="varchar(60) default '' ", nullable=true)
	private String prenom_pere;
	
	@Column(name = "nom_pere", columnDefinition="varchar(40) default '' ", nullable=true)
	private String nom_pere;
	
	@Column(name = "profession_pere", columnDefinition="varchar(60) default '' ", nullable=true)
	private String profession_pere;
	
	@Column(name = "domicile_pere", columnDefinition="varchar(80) default '' ", nullable=true)
	private String domicile_pere;
	
	@Column(name = "prenom_mere", columnDefinition="varchar(60) default '' ", nullable=true)
	private String prenom_mere;
	
	@Column(name = "nom_mere", columnDefinition="varchar(40) default '' ", nullable=true)
	private String nom_mere;
	
	@Column(name = "profession_mere", columnDefinition="varchar(60) default '' ", nullable=true)
	private String profession_mere;
	
	@Column(name = "domicile_mere", columnDefinition="varchar(60) default '' ", nullable=true)
	private String domicile_mere;
	
	@Column(name = "date_creation", columnDefinition="varchar(40) default '' ", nullable=false)
	private String date_creation;
	
	@Column(name = "date_modification", columnDefinition="varchar(40) default '' ", nullable=true)
	private String date_modification;
	
	@Column(name = "etat", columnDefinition="varchar(20) default 'Instance' ", nullable=false)
	private String etat;
	
	@Column(name = "Type_declaration", columnDefinition="varchar(30) default '' ", nullable=false)
	private String type_declaration;
	
	@Column(name = "prenom_declarant", columnDefinition="varchar(60) default '' ", nullable=false)
	private String prenom_declarant;
	
	@Column(name = "nom_declarant", columnDefinition="varchar(40) default '' ", nullable=false)
	private String nom_declarant;
	
	@Column(name = "adresse_declarant", columnDefinition="varchar(80) default '' ", nullable=true)
	private String adresse_declarant;
	
	@Column(name = "profession_declarant", columnDefinition="varchar(60) default '' ", nullable=true)
	private String profession_declarant;
	
	@Column(name = "degre_parente", columnDefinition="varchar(80) default '' ", nullable=false)
	private String degre_parente;
	
	@Column(name = "num_identification_declarant", columnDefinition="varchar(30) default '' ", nullable=false)
	private String num_identification_declarant;
	
	@Column(name = "num_jugement", columnDefinition="varchar(11) default '' ", nullable=true)
	private String num_jugement;
	
	@Column(name = "date_jugement", columnDefinition="varchar(20) default '' ", nullable=true)
	private String date_jugement;
	
	@Column(name = "tribunal", columnDefinition="varchar(40) default '' ", nullable=true)
	private String tribunal;
	
	@Column(name = "mention_marginale", columnDefinition="LONGTEXT")
	private String mention_marginale;
	
	@Column(name = "pays_deces", columnDefinition="varchar(40) default '' ", nullable=true)
	private String pays_deces;
	
	private Date date_naissanceDefunt;
	private Date date_d;
	private Date date_j;
	private Date heure_d;

	@ManyToOne
	(
			cascade={CascadeType.PERSIST, CascadeType.MERGE}
	)
	@JoinColumn(name="createurDeces")
	private Users createurDeces;
	
	@ManyToOne
	(
			cascade={CascadeType.PERSIST, CascadeType.MERGE}
	)
	@JoinColumn(name="modificateurDeces")
	private Users modificateurDeces;
	

	@ManyToOne
	(
			cascade={CascadeType.PERSIST, CascadeType.MERGE}
	)
	@JoinColumn(name="validateurDeces")
	private Users validateurDeces;

    public DeclarationDeces() {
    }

	public DeclarationDeces(String date_deces, String heure_deces,
			String lieu_deces, String formation_sanitaire, String numero_acte,
			String prenom_defunt, String nom_defunt, String sexe_defunt,
			String date_naissance_defunt, String lieu_naissance_defunt,
			String profession_defunt, String domicile_defunt, String marie_a,
			String prenom_pere, String nom_pere, String profession_pere,
			String domicile_pere, String prenom_mere, String nom_mere,
			String profession_mere, String domicile_mere, String date_creation,
			String date_modification, String etat, String type_declaration,
			String prenom_declarant, String nom_declarant,
			String adresse_declarant, String profession_declarant,
			String degre_parente, String num_identification_declarant,
			String num_jugement, String date_jugement, String tribunal,
			String mention_marginale, String pays_deces, Users createurDeces,
			Users modificateurDeces, Users validateurDeces) {
		super();
		this.date_deces = date_deces;
		this.heure_deces = heure_deces;
		this.lieu_deces = lieu_deces;
		this.formation_sanitaire = formation_sanitaire;
		this.numero_acte = numero_acte;
		this.prenom_defunt = prenom_defunt;
		this.nom_defunt = nom_defunt;
		this.sexe_defunt = sexe_defunt;
		this.date_naissance_defunt = date_naissance_defunt;
		this.lieu_naissance_defunt = lieu_naissance_defunt;
		this.profession_defunt = profession_defunt;
		this.domicile_defunt = domicile_defunt;
		this.marie_a = marie_a;
		this.prenom_pere = prenom_pere;
		this.nom_pere = nom_pere;
		this.profession_pere = profession_pere;
		this.domicile_pere = domicile_pere;
		this.prenom_mere = prenom_mere;
		this.nom_mere = nom_mere;
		this.profession_mere = profession_mere;
		this.domicile_mere = domicile_mere;
		this.date_creation = date_creation;
		this.date_modification = date_modification;
		this.etat = etat;
		this.type_declaration = type_declaration;
		this.prenom_declarant = prenom_declarant;
		this.nom_declarant = nom_declarant;
		this.adresse_declarant = adresse_declarant;
		this.profession_declarant = profession_declarant;
		this.degre_parente = degre_parente;
		this.num_identification_declarant = num_identification_declarant;
		this.num_jugement = num_jugement;
		this.date_jugement = date_jugement;
		this.tribunal = tribunal;
		this.mention_marginale = mention_marginale;
		this.pays_deces = pays_deces;
		this.createurDeces = createurDeces;
		this.modificateurDeces = modificateurDeces;
		this.validateurDeces = validateurDeces;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDate_deces() {
		return date_deces;
	}

	public void setDate_deces(String date_deces) {
		this.date_deces = date_deces;
	}

	public String getHeure_deces() {
		return heure_deces;
	}

	public void setHeure_deces(String heure_deces) {
		this.heure_deces = heure_deces;
	}

	public String getLieu_deces() {
		return lieu_deces;
	}

	public void setLieu_deces(String lieu_deces) {
		this.lieu_deces = lieu_deces;
	}

	public String getFormation_sanitaire() {
		return formation_sanitaire;
	}

	public void setFormation_sanitaire(String formation_sanitaire) {
		this.formation_sanitaire = formation_sanitaire;
	}

	public String getNumero_acte() {
		return numero_acte;
	}

	public void setNumero_acte(String numero_acte) {
		this.numero_acte = numero_acte;
	}

	public String getPrenom_defunt() {
		return prenom_defunt;
	}

	public void setPrenom_defunt(String prenom_defunt) {
		this.prenom_defunt = prenom_defunt;
	}

	public String getNom_defunt() {
		return nom_defunt;
	}

	public void setNom_defunt(String nom_defunt) {
		this.nom_defunt = nom_defunt;
	}

	public String getSexe_defunt() {
		return sexe_defunt;
	}

	public void setSexe_defunt(String sexe_defunt) {
		this.sexe_defunt = sexe_defunt;
	}

	public String getDate_naissance_defunt() {
		return date_naissance_defunt;
	}

	public void setDate_naissance_defunt(String date_naissance_defunt) {
		this.date_naissance_defunt = date_naissance_defunt;
	}

	public String getLieu_naissance_defunt() {
		return lieu_naissance_defunt;
	}

	public void setLieu_naissance_defunt(String lieu_naissance_defunt) {
		this.lieu_naissance_defunt = lieu_naissance_defunt;
	}

	public String getProfession_defunt() {
		return profession_defunt;
	}

	public void setProfession_defunt(String profession_defunt) {
		this.profession_defunt = profession_defunt;
	}

	public String getDomicile_defunt() {
		return domicile_defunt;
	}

	public void setDomicile_defunt(String domicile_defunt) {
		this.domicile_defunt = domicile_defunt;
	}

	public String getMarie_a() {
		return marie_a;
	}

	public void setMarie_a(String marie_a) {
		this.marie_a = marie_a;
	}

	public String getPrenom_pere() {
		return prenom_pere;
	}

	public void setPrenom_pere(String prenom_pere) {
		this.prenom_pere = prenom_pere;
	}

	public String getNom_pere() {
		return nom_pere;
	}

	public void setNom_pere(String nom_pere) {
		this.nom_pere = nom_pere;
	}

	public String getProfession_pere() {
		return profession_pere;
	}

	public void setProfession_pere(String profession_pere) {
		this.profession_pere = profession_pere;
	}

	public String getDomicile_pere() {
		return domicile_pere;
	}

	public void setDomicile_pere(String domicile_pere) {
		this.domicile_pere = domicile_pere;
	}

	public String getPrenom_mere() {
		return prenom_mere;
	}

	public void setPrenom_mere(String prenom_mere) {
		this.prenom_mere = prenom_mere;
	}

	public String getNom_mere() {
		return nom_mere;
	}

	public void setNom_mere(String nom_mere) {
		this.nom_mere = nom_mere;
	}

	public String getProfession_mere() {
		return profession_mere;
	}

	public void setProfession_mere(String profession_mere) {
		this.profession_mere = profession_mere;
	}

	public String getDomicile_mere() {
		return domicile_mere;
	}

	public void setDomicile_mere(String domicile_mere) {
		this.domicile_mere = domicile_mere;
	}

	public String getDate_creation() {
		return date_creation;
	}

	public void setDate_creation(String date_creation) {
		this.date_creation = date_creation;
	}

	public String getDate_modification() {
		return date_modification;
	}

	public void setDate_modification(String date_modification) {
		this.date_modification = date_modification;
	}

	public String getEtat() {
		return etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public String getType_declaration() {
		return type_declaration;
	}

	public void setType_declaration(String type_declaration) {
		this.type_declaration = type_declaration;
	}

	public String getPrenom_declarant() {
		return prenom_declarant;
	}

	public void setPrenom_declarant(String prenom_declarant) {
		this.prenom_declarant = prenom_declarant;
	}

	public String getNom_declarant() {
		return nom_declarant;
	}

	public void setNom_declarant(String nom_declarant) {
		this.nom_declarant = nom_declarant;
	}

	public String getAdresse_declarant() {
		return adresse_declarant;
	}

	public void setAdresse_declarant(String adresse_declarant) {
		this.adresse_declarant = adresse_declarant;
	}

	public String getProfession_declarant() {
		return profession_declarant;
	}

	public void setProfession_declarant(String profession_declarant) {
		this.profession_declarant = profession_declarant;
	}

	public String getDegre_parente() {
		return degre_parente;
	}

	public void setDegre_parente(String degre_parente) {
		this.degre_parente = degre_parente;
	}

	public String getNum_identification_declarant() {
		return num_identification_declarant;
	}

	public void setNum_identification_declarant(String num_identification_declarant) {
		this.num_identification_declarant = num_identification_declarant;
	}

	public String getNum_jugement() {
		return num_jugement;
	}

	public void setNum_jugement(String num_jugement) {
		this.num_jugement = num_jugement;
	}

	public String getDate_jugement() {
		return date_jugement;
	}

	public void setDate_jugement(String date_jugement) {
		this.date_jugement = date_jugement;
	}

	public String getTribunal() {
		return tribunal;
	}

	public void setTribunal(String tribunal) {
		this.tribunal = tribunal;
	}

	public String getMention_marginale() {
		return mention_marginale;
	}

	public void setMention_marginale(String mention_marginale) {
		this.mention_marginale = mention_marginale;
	}

	public String getPays_deces() {
		return pays_deces;
	}

	public void setPays_deces(String pays_deces) {
		this.pays_deces = pays_deces;
	}

	public Date getDate_naissanceDefunt() {
		return date_naissanceDefunt;
	}

	public void setDate_naissanceDefunt(Date date_naissanceDefunt) {
		this.date_naissanceDefunt = date_naissanceDefunt;
	}

	public Date getDate_d() {
		return date_d;
	}

	public void setDate_d(Date date_d) {
		this.date_d = date_d;
	}

	public Date getDate_j() {
		return date_j;
	}

	public void setDate_j(Date date_j) {
		this.date_j = date_j;
	}

	public Users getCreateurDeces() {
		return createurDeces;
	}

	public void setCreateurDeces(Users createurDeces) {
		this.createurDeces = createurDeces;
	}

	public Users getModificateurDeces() {
		return modificateurDeces;
	}

	public void setModificateurDeces(Users modificateurDeces) {
		this.modificateurDeces = modificateurDeces;
	}

	public Users getValidateurDeces() {
		return validateurDeces;
	}

	public void setValidateurDeces(Users validateurDeces) {
		this.validateurDeces = validateurDeces;
	}

	public Date getHeure_d() {
		return heure_d;
	}

	public void setHeure_d(Date heure_d) {
		this.heure_d = heure_d;
	}
    
    
    
}


